
General\CustomUIThemePath=/home/svv/.config/qBittorrent/themes/dracula.qbtheme

Downloads\ScanDirsLastPath=/mnt/data/Downloads/Firefox

Downloads\SavePath=/mnt/data/Downloads/Torrent/
Downloads\TempPath=/mnt/data/Downloads/Torrent/.unfinished/
Downloads\TorrentExportDir=/mnt/data/Downloads/Torrent/.torrent_files