# подгружаем путь к скриптам
[ -f ~/.my_scripts.conf ] && source ~/.my_scripts.conf

# rclone (dropbox)
alias dropbox-on='rclone mount --daemon dbx: ~/dbx'
alias dropbox-off='fusermount -u ~/dbx'

# git
## hide changes in indexed files (only for local use)
alias git-hide='git update-index --skip-worktree'
alias git-unhide='git update-index --no-skip-worktree'
alias git-hidden='git ls-files -v | grep "^S"'
## ignore changes in indexed files (only for local use)
alias git-assume='git update-index --assume-unchanged'
alias git-unassume='git update-index --no-assume-unchanged'
alias git-assumed='git ls-files -v | grep "^h"'
## else
alias gitka='gitk --all &'
alias gitfdates="$MYSCRIPTS/git_file_dates.py"

# linux things
alias update-list='source $MYSCRIPTS/utils.sh; apt_update'
alias backupf='f() { cp -fv --backup=numbered "$1" "$1"; }; f'
alias clipf='f() { cat "$1" | xclip -sel clip; }; f'
# вывод размера папок
alias list-size='du -h --max-depth=1 ./ | sort -hr'
# показывает диски в режиме "только для чтения"
alias ro-show='grep "[[:space:]]ro[[:space:],]" /proc/mounts'

# other
alias myscripts-env='source ~/.my_scripts.conf'
alias ecrontabvim='VISUAL=vim crontab -e'
alias ecrontabnvim='VISUAL=nvim crontab -e'
alias mc='LANG=C.utf8 mc'